GET http://localhost:3000/blocks


###


POST http://localhost:3000/blocks
content-type: application/json

{
    "data": "Third block!!"
}


###

POST http://localhost:3000/peers
content-type: application/json

{
    "peer": "ws://localhost:4000"
}
